export type IndexCode = 'NIFTY50' | 'NIFTY100' | 'NIFTY200' | 'NIFTY500' | 'MIDCAP' | 'SMALLCAP'

// Minimal curated sets to keep calls bounded; can be expanded later
export const INDICES: Record<IndexCode, string[]> = {
  NIFTY50: [
    'RELIANCE','TCS','HDFCBANK','INFY','ICICIBANK','HINDUNILVR','BHARTIARTL','ITC','KOTAKBANK','LT','SBIN','ASIANPAINT','MARUTI','BAJFINANCE','HCLTECH','AXISBANK','WIPRO','ONGC','TATAMOTORS','SUNPHARMA','ULTRACEMCO','TECHM','TITAN','POWERGRID','NESTLEIND','JSWSTEEL','NTPC','BAJAJFINSV','DRREDDY','TATACONSUM','HEROMOTOCO','BRITANNIA','COALINDIA','CIPLA','DIVISLAB','EICHERMOT','GRASIM','HINDALCO','INDUSINDBK','SHREECEM','TATASTEEL','ADANIPORTS','APOLLOHOSP','BPCL','GODREJCP','HDFCLIFE','ICICIPRULI','SBILIFE','M&M','PIDILITIND'
  ],
  // For demo, NIFTY100 extends NIFTY50 with additional large caps
  NIFTY100: [
    'RELIANCE','TCS','HDFCBANK','INFY','ICICIBANK','HINDUNILVR','BHARTIARTL','ITC','KOTAKBANK','LT','SBIN','ASIANPAINT','MARUTI','BAJFINANCE','HCLTECH','AXISBANK','WIPRO','ONGC','TATAMOTORS','SUNPHARMA','ULTRACEMCO','TECHM','TITAN','POWERGRID','NESTLEIND','JSWSTEEL','NTPC','BAJAJFINSV','DRREDDY','TATACONSUM','HEROMOTOCO','BRITANNIA','COALINDIA','CIPLA','DIVISLAB','EICHERMOT','GRASIM','HINDALCO','INDUSINDBK','SHREECEM','TATASTEEL','ADANIPORTS','APOLLOHOSP','BPCL','GODREJCP','HDFCLIFE','ICICIPRULI','SBILIFE','M&M','PIDILITIND',
    'LTIM','DMART','DLF','BAJAJ-AUTO','HAVELLS','JSWENERGY','ADANIENTERPRISES','ADANIGREEN','ADANITRANS','SRF','TVSMOTOR','AUROPHARMA','BERGEPAINT','COLPAL','DABUR','NAUKRI','HINDZINC','INDIGO','MUTHOOTFIN','PEL','RECLTD','SIEMENS','TATAPOWER','UBL','VEDL','VOLTAS','ZOMATO','COFORGE','MPHASIS','INDIGO','LUPIN','GAIL','GLAND','SHRIRAMFIN','ABB','BIOCON','INDIGO' 
  ],
  // NIFTY200 extends NIFTY100 with more midcaps (sample list)
  NIFTY200: ['NIFTY50','NIFTY100','BANDHANBNK','CANBK','BANKBARODA','FEDERALBNK','PNB','IDFCFIRSTB','LICHSGFIN','ICICIGI','ICICIPRULI','TATACOMM','BEL','BHEL','M&MFIN','MANAPPURAM','AMBUJACEM','ACC','RAMCOCEM','PETRONET','PIIND','PERSISTENT','PAGEIND','TRENT','BALRAMCHIN','CHOLAFIN','COROMANDEL','CUMMINSIND','DIXON','EXIDEIND','GUJGASLTD','HONAUT','INDHOTEL','OFSS','TORNTPOWER','TORNTPHARM','WHIRLPOOL'],
  // NIFTY500 extends with smallcaps (compressed for demo)
  NIFTY500: ['NIFTY200','CENTURYTEX','ASHOKLEY','ATGL','BANKINDIA','BATAINDIA','BPCL','CESC','DEEPAKNTR','ESCORTS','FORTIS','GRANULES','GODREJPROP','IEX','INDIAMART','INDIGO','IRCTC','JINDALSTEL','JUBLFOOD','METROPOLIS','MINDTREE','MOTHERSON','NMDC','PFC','POLYCAB','RAIN','RBLBANK','SAIL','TATAELXSI','TATACHEM','UJJIVANSFB','UNITDSPR','ZEEL'],
  MIDCAP: ['LTIM','DMART','DLF','HAVELLS','JSWENERGY','SRF','TVSMOTOR','AUROPHARMA','BERGEPAINT','COLPAL','DABUR','NAUKRI','HINDZINC','MUTHOOTFIN','PEL','RECLTD','SIEMENS','TATAPOWER','UBL','VOLTAS','COFORGE','MPHASIS','LUPIN','GAIL','GLAND','SHRIRAMFIN','ABB','BIOCON'],
  SMALLCAP: ['BANDHANBNK','CANBK','FEDERALBNK','PNB','LICHSGFIN','TATACOMM','BEL','BHEL','M&MFIN','MANAPPURAM','AMBUJACEM','ACC','RAMCOCEM','PETRONET','PIIND','PERSISTENT','PAGEIND','TRENT','BALRAMCHIN','CHOLAFIN','COROMANDEL','CUMMINSIND','DIXON','EXIDEIND','GUJGASLTD','HONAUT','INDHOTEL','OFSS','TORNTPOWER','TORNTPHARM','WHIRLPOOL']
}

export function resolveSymbols(input: Array<string | IndexCode>): string[] {
  const set = new Set<string>()
  for (const item of input) {
    if (item in INDICES) {
      for (const s of INDICES[item as IndexCode]) set.add(s)
    } else {
      set.add(String(item).toUpperCase())
    }
  }
  return Array.from(set)
}


